### ISSUE TITLE
npm run dev 报错 项目运行不起来

### ISSUE THREAD

**Issue by ITLMXMF222** [codecatdog/three#10]
error  in ./node_modules/three/build/three.module.js

Module parse failed: Unexpected token (2516:25)
You may need an appropriate loader to handle this file type.
|
|               this.texture = source.texture.clone();
|               this.texture.image = { ...this.texture.image }; // See #20328.
|
|               this.depthBuffer = source.depthBuffer;

 @ ./src/common/tool/OrbitControls.js 11:0-139
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/Three.
vue
 @ ./src/components/Three.vue
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by ling-zer** [comment]
`You may need an appropriate loader to handle this file type.`看起来是webpack的配置问题，你可以检查一下是不是版本问题。
