### ISSUE TITLE
为什么我把你的代码copy下来然后换了模型，只显示三个坐标轴，不显示模型呢？

### ISSUE THREAD

**Issue by zoulx-0717** [codecatdog/three#8]

**Comment by ling-zer** [comment]
1，确保加载的模型是obj文件；
2，模型是否加载成功可通过浏览器开发工具查看，如果加载失败，考虑是obj文件有问题；
3，由于实际模型太大，我在代码中对模型进行了缩小，这个缩放倍数可根据你的模型调整，太大太小都可能导致看不见。

**Comment by zoulx-0717** [comment]
> 1，确保加载的模型是obj文件；
> 2，模型是否加载成功可通过浏览器开发工具查看，如果加载失败，考虑是obj文件有问题；
> 3，由于实际模型太大，我在代码中对模型进行了缩小，这个缩放倍数可根据你的模型调整，太大太小都可能导致看不见。

谢谢大神指点！
